name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  

  flutter:

    sdk: flutter

  intl: ^0.18.0
 
  cupertino_icons: ^1.0.8
  
  
  # --- FIREBASE DEPENDENCIES FOR LAZA PROJECT ---
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Ensure your assets are declared here later for product images
  # assets:
  #   - assets/images/